export type EnumTone = 'danger' | 'info' | 'primary' | 'success' | 'warning';

const labels: Record<string, string> = {
  approve: '通过',
  reject: '拒绝',
  escalate: '升级复核',
  ai_generated: 'AI 生成',
  operator_created: '运营创建',
  uploading: '上传中',
  distributing: '分发中',
  partially_picked: '部分拾取',
  conversation_created: '已创建会话',
  user_deleted: '用户已删除',
  not_submitted: '未提交',
  waiting_review: '等待审核',
  ready_to_send: '待发送',
  retrying: '重试中',
  notification_failed: '通知失败',
  chargeback: '拒付',
  payment_failed: '支付失败',
  fulfillment_failed: '履约失败',
  grace_period: '宽限期',
  feature_unlock: '永久权益',
  purchase: '购买',
  renewal: '续订',
  refund: '退款',
  revocation: '撤销',
  restore: '恢复',
  pending_profile: '待完善资料',
  deleting: '注销冷静期',
  content_removed: '内容下架',
  send_restricted: '限制发送',
  pick_restricted: '限制捞取',
  chat_restricted: '限制聊天',
  temporary_suspension: '临时封禁',
  permanent_ban: '永久封禁',
  device_restricted: '限制设备',
  info: '信息',
  android: 'Android',
  ios: 'iOS',
  web: '网页',
  bottle: '漂流瓶',
  message: '消息',
  media: '媒体',
  report: '举报',
  penalty: '处罚',
  appeal: '申诉',
  order: '订单',
  admin_manual: '管理员操作',
  owner: '所有者',
  member: '成员',
  participant: '参与者',
  grant: '授予',
  consume: '消耗',
  revoke: '撤销',
  expire: '到期',
  daily_quota: '每日配额',
  one_time_quota: '单次配额',
  permanent: '永久',
  matched: '匹配成功',
  skipped: '已跳过',
  exhausted: '已耗尽',
  coin_shortfall: '金币余额不足',
  partial_refund: '部分退款待核验',
  active: '生效中',
  admin: '管理员',
  admin_removed: '已下架',
  ai: 'AI',
  appealed: '已申诉',
  appeal_resolved: '申诉已处理',
  apple: 'Apple',
  approved: '已通过',
  archived: '已归档',
  assigned: '已分派',
  available: '可用',
  awaiting_approval: '待复核',
  banned: '已封禁',
  cancelled: '已取消',
  cancel_pending: '取消中',
  closed: '已关闭',
  closed_duplicate: '重复结案',
  coin_pack: '金币包',
  completed: '已完成',
  configured: '已配置',
  created: '已创建',
  critical: '严重',
  customer_service: '客服',
  degraded: '异常',
  deleted: '已删除',
  delivered: '已送达',
  denied: '已拒绝',
  disabled: '已停用',
  draft: '草稿',
  email: '邮箱',
  enabled: '已启用',
  expired: '已过期',
  failed: '失败',
  false: '否',
  fulfilled: '已履约',
  generated: '已生成',
  generating: '生成中',
  google: 'Google',
  google_play: 'Google Play',
  app_store: 'App Store',
  high: '高',
  image: '图片',
  in_review: '审核中',
  inactive: '未启用',
  low: '低',
  manual_review: '人工复核',
  medium: '中',
  normal: '正常',
  notified: '已通知',
  open: '待处理',
  paid: '已支付',
  paused: '已暂停',
  pending: '待处理',
  pending_review: '待审核',
  pending_payment: '待支付',
  processing: '处理中',
  published: '已发布',
  queued: '排队中',
  read: '已读',
  ready: '已就绪',
  ready_to_publish: '待发布',
  recalled: '已撤回',
  refunded: '已退款',
  refunding: '退款中',
  refused: '已拒绝',
  rejected: '已拒绝',
  resolved: '已解决',
  resolved_approved: '申诉通过',
  resolved_invalid: '举报不成立',
  resolved_rejected: '申诉驳回',
  resolved_valid: '举报属实',
  restricted: '受限',
  retired: '已退役',
  revoked: '已撤销',
  reviewing: '审核中',
  running: '运行中',
  scheduled: '已预约',
  sent: '已发送',
  send_failed: '发送失败',
  submitted: '已提交',
  subscription: '订阅',
  succeeded: '成功',
  success: '成功',
  suspended: '已暂停',
  system: '系统',
  text: '文字',
  triaging: '分诊中',
  true: '是',
  unconfigured: '未配置',
  unobserved: '尚未观测',
  urgent: '紧急',
  user: '用户',
  user_to_user: '用户会话',
  user_to_ai: 'AI 会话',
  verified: '已验证',
  virtual: '虚拟身份',
  virtual_identity: '虚拟身份',
  voice: '语音',
  waiting: '等待中',
  warning: '警告',
};

const tones: Array<[EnumTone, Set<string>]> = [
  [
    'success',
    new Set([
      '1',
      'active',
      'approve',
      'approved',
      'available',
      'completed',
      'configured',
      'conversation_created',
      'delivered',
      'enabled',
      'fulfilled',
      'generated',
      'low',
      'matched',
      'normal',
      'notified',
      'paid',
      'published',
      'read',
      'ready',
      'resolved',
      'resolved_approved',
      'resolved_valid',
      'sent',
      'succeeded',
      'success',
      'true',
      'verified',
    ]),
  ],
  [
    'danger',
    new Set([
      'admin_removed',
      'banned',
      'chargeback',
      'coin_shortfall',
      'content_removed',
      'critical',
      'degraded',
      'deleted',
      'denied',
      'failed',
      'fulfillment_failed',
      'high',
      'notification_failed',
      'payment_failed',
      'permanent_ban',
      'refused',
      'reject',
      'rejected',
      'resolved_invalid',
      'resolved_rejected',
      'restricted',
      'send_failed',
      'temporary_suspension',
      'urgent',
    ]),
  ],
  [
    'warning',
    new Set([
      'appealed',
      'assigned',
      'awaiting_approval',
      'cancel_pending',
      'chat_restricted',
      'created',
      'deleting',
      'device_restricted',
      'distributing',
      'escalate',
      'generating',
      'grace_period',
      'in_review',
      'manual_review',
      'medium',
      'open',
      'partial_refund',
      'partially_picked',
      'pending',
      'pending_payment',
      'pending_profile',
      'pending_review',
      'pick_restricted',
      'processing',
      'queued',
      'ready_to_publish',
      'ready_to_send',
      'refunding',
      'retrying',
      'reviewing',
      'running',
      'scheduled',
      'send_restricted',
      'submitted',
      'triaging',
      'unconfigured',
      'uploading',
      'waiting',
      'waiting_review',
      'warning',
    ]),
  ],
  [
    'primary',
    new Set([
      'admin',
      'ai',
      'ai_generated',
      'android',
      'app_store',
      'appeal',
      'appeal_resolved',
      'apple',
      'bottle',
      'coin_pack',
      'customer_service',
      'daily_quota',
      'email',
      'feature_unlock',
      'google',
      'google_play',
      'grant',
      'image',
      'ios',
      'media',
      'member',
      'message',
      'one_time_quota',
      'operator_created',
      'order',
      'owner',
      'participant',
      'penalty',
      'permanent',
      'purchase',
      'renewal',
      'report',
      'restore',
      'subscription',
      'system',
      'text',
      'user',
      'user_to_ai',
      'user_to_user',
      'virtual',
      'virtual_identity',
      'voice',
      'web',
    ]),
  ],
];

export function enumPresentation(
  value: boolean | null | number | string | undefined,
) {
  if (value === null || value === undefined || value === '') {
    return { empty: true, label: '—', tone: 'info' as EnumTone };
  }
  const key = String(value).toLowerCase();
  return {
    empty: false,
    label: labels[key] ?? String(value),
    tone: tones.find(([, values]) => values.has(key))?.[0] ?? 'info',
  };
}
